version: '2'
services:
  zk:
    #alpine
    image: cdelgehier/zookeeper
    network_mode: host
    environment:
      ZK_CONFIG: tickTime=2000,initLimit=10,syncLimit=5,maxClientCnxns=128,forceSync=no,clientPort=2181
      ZK_ID: 1
      ZOO_LOG_DIR: /var/log/zookeeper
 
  mesos_master:
    #ubuntu
    image: mesosphere/mesos-master:0.28.1-2.0.20.ubuntu1404
    network_mode: host
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      MESOS_ZK: zk://127.0.0.1:2181/mesos
      MESOS_HOSTNAME: 127.0.0.1
      MESOS_IP: 127.0.0.1
      MESOS_QUORUM: 1
      MESOS_CLUSTER: docker-compose
      MESOS_WORK_DIR: /var/lib/mesos
    depends_on:
      - zk

  mesos_slave:
    #ubuntu
    image: mesosphere/mesos-slave:0.28.1-2.0.20.ubuntu1404
    network_mode: host
    pid: host
    privileged: true
    environment:
      MESOS_MASTER: zk://127.0.0.1:2181/mesos
      MESOS_HOSTNAME: 127.0.0.1
      MESOS_IP: 127.0.0.1
      MESOS_CONTAINERIZERS: docker,mesos
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /usr/bin/docker:/usr/bin/docker:ro
      - /usr/lib/x86_64-linux-gnu/libapparmor.so.1:/usr/lib/x86_64-linux-gnu/libapparmor.so.1:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /lib/x86_64-linux-gnu/libsystemd-journal.so.0:/lib/x86_64-linux-gnu/libsystemd-journal.so.0      
    depends_on:
      - zk

  marathon:
    #ubuntu
    image: mesosphere/marathon:v1.1.1
    network_mode: host
    environment:
      MARATHON_MASTER: zk://127.0.0.1:2181/mesos
      MARATHON_ZK: zk://127.0.0.1:2181/marathon
      MARATHON_HOSTNAME: 127.0.0.1
    command: --event_subscriber http_callback
    depends_on:
      - zk

  # chronos:
  #   #ubuntu
  #   image: mesosphere/chronos:chronos-2.4.0-0.1.20151007110204.ubuntu1404-mesos-0.24.1-0.2.35.ubuntu1404
  #   command: /usr/bin/chronos run_jar --http_port 8888 --master zk://127.0.0.1:2181/mesos --zk_hosts zk://127.0.0.1:2181/mesos
  #   network_mode: host
  #   depends_on:
  #     - zk
